const ADD_PRODUCT = "ADD_PRODUCT";
const REMOVE_PRODUCT = "REMOVE_PRODUCT";
const SET_STATE = "SET_STATE";
const ADD_NOTIFICATION = "ADD_NOTIFICATION";

export {ADD_PRODUCT, REMOVE_PRODUCT, SET_STATE, ADD_NOTIFICATION};
